# Generated by Django 5.2.6 on 2025-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='رابط فيديو المنتج (يوتيوب)'),
        ),
    ]
