# Generated by Django 5.2.6 on 2025-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_author_product_isbn_product_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='ملف الكتاب (PDF, EPUB)'),
        ),
    ]
