# Generated by Django 5.2.6 on 2025-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address_order_country_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmation_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_box1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_box2',
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم البطاقة'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رمز التأكيد'),
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم الأخير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي'),
        ),
    ]
