# Generated by Django 5.2.6 on 2025-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_payment_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف'),
        ),
    ]
